// Auto-generated by migrate-prompts-fixed.js
// Generated on: 2025-06-17T13:29:45.197Z

import type { AdvancedPrompt } from './types';

export const advancedpromptPrompts: AdvancedPrompt[] = [
  {
    "id": "ed-lp-03",
    "categoryId": "education",
    "subcategoryId": "lesson-planning",
    "promptGroupId": "instructional-materials",
    "title": "Math Concept Visual Aid",
    "description": "Design a visual aid to explain a challenging math concept.",
    "prompt": "Create a detailed plan for a visual aid that explains the concept of fractions to 4th-grade students. The visual aid should: 1) Clearly demonstrate how fractions represent parts of a whole, 2) Include at least three different representations (e.g., circle fractions, number line, real-world examples), 3) Be interactive or allow for student manipulation, 4) Include a brief teacher guide with discussion questions, and 5) Provide extension activities for advanced learners. Describe the materials needed and step-by-step instructions for creating the visual aid.",
    "tags": [
      "math",
      "visual learning",
      "elementary education"
    ],
    "estimatedTime": "30-45 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "createdAt": "2025-06-17T13:29:45.195Z",
    "difficulty": "Advanced",
    "expectedOutcome": "Comprehensive solution ready for implementation",
    "followUpActions": [
      "Review with team",
      "Test in staging"
    ],
    "complexityFactors": [
      "Multiple components",
      "Integration requirements"
    ],
    "industryContext": "Cross-industry application"
  },
  {
    "id": "ed-cm-02",
    "categoryId": "education",
    "subcategoryId": "classroom-management",
    "promptGroupId": "routines-procedures",
    "title": "First Week Classroom Routines",
    "description": "Design procedures for the first week of school to establish routines.",
    "prompt": "Create a detailed plan for teaching classroom routines during the first week of school for a middle school classroom. Include: 1) A list of 5-7 essential routines to teach (e.g., entering the classroom, turning in work, group work transitions), 2) Step-by-step instructions for teaching each routine, 3) Practice activities to reinforce the routines, 4) A system for reviewing and reinforcing routines throughout the first month, and 5) Strategies for addressing students who struggle with routines. Provide specific language and examples of how you would explain and model each routine to students.",
    "tags": [
      "routines",
      "back to school",
      "classroom procedures"
    ],
    "estimatedTime": "30-45 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "createdAt": "2025-06-17T13:29:45.195Z",
    "difficulty": "Advanced",
    "expectedOutcome": "Comprehensive solution ready for implementation",
    "followUpActions": [
      "Review with team",
      "Test in staging"
    ],
    "complexityFactors": [
      "Multiple components",
      "Integration requirements"
    ],
    "industryContext": "Cross-industry application"
  },
  {
    "id": "ed-ae-01",
    "categoryId": "education",
    "subcategoryId": "assessment-evaluation",
    "promptGroupId": "formative-assessment",
    "title": "Formative Assessment Strategies",
    "description": "Create a set of formative assessment strategies for a unit.",
    "prompt": "Develop a comprehensive set of formative assessment strategies for a 6th-grade science unit on ecosystems. Include: 1) At least five different types of formative assessments (e.g., exit tickets, think-pair-share, one-minute papers), 2) Clear learning targets for each assessment, 3) Specific success criteria, 4) Methods for providing timely feedback to students, and 5) Strategies for using assessment data to inform instruction. Provide examples of assessment prompts or questions for each strategy.",
    "tags": [
      "assessment",
      "formative assessment",
      "teaching strategies"
    ],
    "estimatedTime": "30-45 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "createdAt": "2025-06-17T13:29:45.195Z",
    "difficulty": "Advanced",
    "expectedOutcome": "Comprehensive solution ready for implementation",
    "followUpActions": [
      "Review with team",
      "Test in staging"
    ],
    "complexityFactors": [
      "Multiple components",
      "Integration requirements"
    ],
    "industryContext": "Cross-industry application"
  }
];
