// Auto-generated by migrate-prompts-fixed.js
// Generated on: 2025-06-17T13:29:45.195Z

import type { BeginnerPrompt } from './types';

export const beginnerpromptPrompts: BeginnerPrompt[] = [
  {
    "id": "ed-lp-01",
    "categoryId": "education",
    "subcategoryId": "lesson-planning",
    "promptGroupId": "lesson-plans",
    "title": "Interactive Science Lesson Plan",
    "description": "Create a 60-minute interactive science lesson plan for middle school students.",
    "prompt": "Design a 60-minute interactive science lesson plan for middle school students (grades 6-8) on the topic of \"The Water Cycle.\" The lesson should include: 1) A 10-minute engaging introduction with a demonstration or thought-provoking question, 2) A 20-minute hands-on activity or experiment, 3) A 15-minute group discussion or presentation, 4) A 10-minute formative assessment, and 5) A 5-minute wrap-up with key takeaways. Include any necessary materials, safety considerations, and differentiation strategies for diverse learners.",
    "tags": [
      "science",
      "middle school",
      "hands-on learning"
    ],
    "estimatedTime": "15-20 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "difficulty": "Easy"
  },
  {
    "id": "ed-lp-04",
    "categoryId": "education",
    "subcategoryId": "lesson-planning",
    "promptGroupId": "differentiation-strategies",
    "title": "Differentiated Instruction for Diverse Learners",
    "description": "Develop strategies to adapt a lesson for students with varying ability levels.",
    "prompt": "For a 7th-grade social studies lesson on ancient civilizations, create a differentiation strategy that accommodates: 1) English Language Learners (ELLs) at beginning and intermediate levels, 2) Students with learning disabilities (e.g., dyslexia, ADHD), 3) Gifted and talented students, and 4) Students with limited access to technology at home. For each group, provide specific modifications to: content delivery, student activities, assessment methods, and available resources. Include at least three different instructional strategies (e.g., tiered assignments, learning centers, choice boards) and explain how you would implement them in a classroom setting.",
    "tags": [
      "differentiation",
      "inclusion",
      "teaching strategies"
    ],
    "estimatedTime": "15-20 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "difficulty": "Easy"
  },
  {
    "id": "ed-cm-03",
    "categoryId": "education",
    "subcategoryId": "classroom-management",
    "promptGroupId": "classroom-community",
    "title": "Building Classroom Community Activities",
    "description": "Design activities to build a positive classroom community.",
    "prompt": "Develop a month-long series of activities to build a strong classroom community in a diverse 3rd-grade classroom. The plan should include: 1) Daily 5-minute community-building activities for the first month, 2) Weekly longer activities (15-20 minutes) that promote collaboration and understanding, 3) Strategies for incorporating student voices and cultural backgrounds, 4) Reflection activities to help students articulate what they're learning about their classmates, and 5) Ways to involve families in the community-building process. Include modifications for virtual or hybrid learning environments.",
    "tags": [
      "community building",
      "social-emotional learning",
      "elementary education"
    ],
    "estimatedTime": "15-20 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "difficulty": "Moderate"
  },
  {
    "id": "ed-ae-02",
    "categoryId": "education",
    "subcategoryId": "assessment-evaluation",
    "promptGroupId": "rubric-design",
    "title": "Project-Based Learning Rubric",
    "description": "Design a rubric for assessing project-based learning activities.",
    "prompt": "Create a detailed rubric for assessing student projects in an 8th-grade social studies class where students create a documentary about a historical event. The rubric should include: 1) 4-6 key criteria (e.g., historical accuracy, research quality, presentation skills), 2) A 4-point scale for each criterion with clear descriptors for each level, 3) Space for specific feedback, 4) A self-assessment component for students, and 5) A peer assessment component. Ensure the rubric aligns with relevant learning standards and includes both content and presentation elements.",
    "tags": [
      "assessment",
      "rubrics",
      "project-based learning"
    ],
    "estimatedTime": "15-20 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "difficulty": "Easy"
  }
];
