// Auto-generated by migrate-prompts-fixed.js
// Generated on: 2025-06-17T13:29:45.196Z
// Updated to fix TypeScript errors on: 2025-06-20

import type { IntermediatePrompt } from './types';

export const intermediatepromptPrompts: IntermediatePrompt[] = [
  {
    "id": "ed-lp-02",
    "categoryId": "education",
    "subcategoryId": "lesson-planning",
    "promptGroupId": "activity-design",
    "title": "Group Activity for Literature Analysis",
    "description": "Design a collaborative group activity for analyzing a novel or short story.",
    "prompt": "Create a detailed group activity for high school students (grades 9-12) to analyze character development in a novel. The activity should: 1) Take approximately 45 minutes, 2) Include specific roles for each group member (e.g., Character Analyst, Quote Finder, Theme Identifier, Presenter), 3) Incorporate both individual and collaborative components, 4) Include a clear rubric for assessment, and 5) Allow for creative presentation of findings. Provide instructions for implementation and suggestions for differentiation based on student ability levels.",
    "tags": [
      "literature",
      "group work",
      "critical thinking"
    ],
    "estimatedTime": "20-30 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "difficulty": "Moderate",
    "expectedOutcome": "Practical application of the concept",
    "followUpActions": [
      "Review materials",
      "Practice implementation"
    ]
  },
  {
    "id": "ed-cm-04",
    "categoryId": "education",
    "subcategoryId": "classroom-management",
    "promptGroupId": "classroom-organization",
    "title": "Flexible Seating Arrangement",
    "description": "Design a flexible seating arrangement for an active learning environment.",
    "prompt": "Design a flexible seating arrangement for a 5th-grade classroom with 28 students that supports various learning activities (whole group, small group, independent work). The plan should include: 1) A detailed classroom diagram with furniture placement, 2) A list of required furniture and materials, 3) Guidelines for students on choosing and using different seating options, 4) A system for managing seating choices, 5) Strategies for ensuring all students can see the board and access materials, and 6) Considerations for students with special needs. Include a brief explanation of how each area of the classroom supports different types of learning activities.",
    "tags": [
      "classroom design",
      "flexible seating",
      "active learning"
    ],
    "estimatedTime": "20-30 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "difficulty": "Challenging",
    "expectedOutcome": "Practical application of the concept",
    "followUpActions": [
      "Review materials",
      "Practice implementation"
    ]
  },
  {
    "id": "ed-ae-03",
    "categoryId": "education",
    "subcategoryId": "assessment-evaluation",
    "promptGroupId": "formative-assessments",
    "title": "Formative Assessment Strategy",
    "description": "Develop a comprehensive formative assessment strategy for a unit of study.",
    "prompt": "Create a comprehensive formative assessment strategy for a 4-week high school biology unit on genetics. The strategy should include: 1) At least five different types of formative assessments (e.g., exit tickets, think-pair-share, one-minute papers, concept maps), 2) A timeline showing when each assessment will be used, 3) Specific learning targets each assessment addresses, 4) Methods for providing timely feedback to students, 5) Strategies for using assessment data to inform instruction, and 6) Differentiation for diverse learners. Include a brief reflection on how this approach supports student learning and informs your teaching practice.",
    "tags": [
      "assessment",
      "formative assessment",
      "teaching strategies"
    ],
    "estimatedTime": "20-30 minutes",
    "prerequisites": [
      "Basic understanding of the topic"
    ],
    "difficulty": "Advanced",
    "expectedOutcome": "Practical application of the concept",
    "followUpActions": [
      "Review materials",
      "Practice implementation"
    ]
  }
];
